POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiYXJta0Bkb2UuY29tIiwiaWF0IjoxNzQyODcyNjUzLCJleHAiOjE3NDI4NzYyNTMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.vHoKR7dFhEWVGV0XuGostAHdNarHVmIcRtO66g_X7b8

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTc0Mjg3MjY1MywiZXhwIjoxNzQyOTU5MDUzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.5Bwu_aAgVrmbdt9H5QLhk8Bp2_KgDdp3Q4yMb0MzT-A"
}